src/main/java/fr/cnrs/opentheso/bean/graph/DataGraphView.java
package fr.cnrs.opentheso.bean.graph;

import fr.cnrs.opentheso.bdd.helper.PreferencesHelper;
import fr.cnrs.opentheso.bdd.helper.SearchHelper;
import fr.cnrs.opentheso.bdd.helper.ThesaurusHelper;
import fr.cnrs.opentheso.bdd.helper.nodes.NodeIdValue;
import fr.cnrs.opentheso.bdd.helper.nodes.search.NodeSearchMini;
import java.io.IOException;
import java.io.Serializable;
import java.util.*;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.ws.rs.core.UriBuilder;

import fr.cnrs.opentheso.bean.menu.connect.Connect;
import fr.cnrs.opentheso.ws.openapi.helper.d3jsgraph.IdValuePair;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.tuple.ImmutablePair;
import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.EagerResult;
import org.neo4j.driver.GraphDatabase;
import org.neo4j.driver.QueryConfig;
import org.primefaces.PrimeFaces;

/**
 *
 * @author miledrousset
 */
@Named
@SessionScoped
public class DataGraphView implements Serializable {

    @Inject
    private Connect connect;
    private List<GraphObject> graphObjects;

    private GraphObject selectedGraph;

    @Inject
    private GraphService graphService;

    private int selectedViewId;
    private String newViewName;
    private String newViewDescription;
    private String newViewDataToAdd;
    private List<ImmutablePair<String, String>> newViewExportedData;
    
    private String selectedIdTheso;
    private NodeSearchMini searchSelected;    

    private Properties getPrefOfNeo4j(){
        ResourceBundle resourceBundle = getBundlePool();
        if(resourceBundle == null){
            return null;
        }
        Properties props = new Properties();
        props.setProperty("neo4j.serverName", resourceBundle.getString("neo4j.serverName"));
        props.setProperty("neo4j.serverPort", resourceBundle.getString("neo4j.serverPort"));
        props.setProperty("neo4j.user", resourceBundle.getString("neo4j.user"));
        props.setProperty("neo4j.password", resourceBundle.getString("neo4j.password"));
        props.setProperty("neo4j.databaseName", resourceBundle.getString("neo4j.databaseName"));        
        
        return props;
        
    }
    private ResourceBundle getBundlePool(){
        FacesContext context = FacesContext.getCurrentInstance();
        try {
            ResourceBundle bundlePool = context.getApplication().getResourceBundle(context, "conHikari");
            return bundlePool;
        } catch (Exception e) {
            System.err.println(e.toString());
        }
        return null;
    }    
    
    
    /**
     * permet de retourner la liste des concepts possibles pour ajouter une
     * relation NT (en ignorant les relations interdites) on ignore les concepts
     * de type TT on ignore les concepts de type RT
     *
     * @param value
     * @return
     */
    public List<NodeSearchMini> getAutoComplete(String value) {
        List<NodeSearchMini> liste = new ArrayList<>();
        SearchHelper searchHelper = new SearchHelper();
        PreferencesHelper preferencesHelper = new PreferencesHelper();
        String idLang = preferencesHelper.getWorkLanguageOfTheso(connect.getPoolConnexion(), selectedIdTheso);
        
        if (selectedIdTheso != null && idLang != null) {
            liste = searchHelper.searchAutoCompletionForRelation(
                    connect.getPoolConnexion(),
                    value,
                    idLang,
                    selectedIdTheso, true);
        }
        return liste;
    }  

    public String getSelectedIdTheso() {
        return selectedIdTheso;
    }

    public void setSelectedIdTheso(String selectedIdTheso) {
        this.selectedIdTheso = selectedIdTheso;
    }

    public NodeSearchMini getSearchSelected() {
        return searchSelected;
    }

    public void setSearchSelected(NodeSearchMini searchSelected) {
        this.searchSelected = searchSelected;
    }


    public void actionAjax(){
    }
    
    
    
    
    public int getSelectedViewId() {
        return selectedViewId;
    }

    public void setSelectedViewId(int selectedViewId) {
        this.selectedViewId = selectedViewId;
    }

    public String getNewViewDataToAdd() {
        return newViewDataToAdd;
    }

    public void setNewViewDataToAdd(String newViewDataToAdd) {
        this.newViewDataToAdd = newViewDataToAdd;
    }

    public String getNewViewName() {
        return newViewName;
    }

    public void setNewViewName(String newViewName) {
        this.newViewName = newViewName;
    }

    public String getNewViewDescription() {
        return newViewDescription;
    }

    public void setNewViewDescription(String newViewDescription) {
        this.newViewDescription = newViewDescription;
    }

    public List<ImmutablePair<String, String>> getNewViewExportedData() {
        return newViewExportedData;
    }

    public void setNewViewExportedData(List<ImmutablePair<String, String>> newViewExportedData) {
        this.newViewExportedData = newViewExportedData;
    }

    public void init() {
        graphObjects = new ArrayList<>(graphService.getViews().values());
        selectedIdTheso = null;
        searchSelected = null;
    }

    public void initNewViewDialog() {
        selectedViewId = -1;
        newViewName = null;
        newViewDescription = null;
        newViewDataToAdd = null;
        newViewExportedData = new ArrayList<>();
    }

    public void initEditViewDialog(String id) {
        GraphObject viewToEdit = graphService.getView(id);
        if (viewToEdit == null) {
            return;
        }
        selectedViewId = viewToEdit.getId();
        newViewName = viewToEdit.getName();
        newViewDescription = viewToEdit.getDescription();
        newViewDataToAdd = null;
        newViewExportedData = viewToEdit.getExportedData();
    }

    public List<GraphObject> getGraphObjects() {
        return graphObjects;
    }

    public void setService(GraphService graphService) {
        this.graphService = graphService;
    }

    public GraphObject getSelectedGraphObject() {
        return selectedGraph;
    }

    public void setSelectedProduct(GraphObject selectedGraph) {
        this.selectedGraph = selectedGraph;
    }

    public void clearMultiViewState() {
        FacesContext context = FacesContext.getCurrentInstance();
        String viewId = context.getViewRoot().getViewId();
        PrimeFaces.current().multiViewState().clearAll(viewId, true, this::showMessage);
    }

    public void redirectToGraphVisualization(String viewId) throws IOException {
        System.out.println("visualisation " + viewId);
        GraphObject view = graphService.getView(viewId);

        if (view == null) {
            return;
        }
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();

        String opethesoUrl = context.getRequestScheme() + "://" + context.getRequestServerName()
                + (Objects.equals(context.getRequestServerName(), "localhost") ? ":" + context.getRequestServerPort() : "")
                + context.getApplicationContextPath();

        final String baseDataURL = opethesoUrl + "/openapi/v1/graph/getData";
        UriBuilder url = UriBuilder.fromUri(baseDataURL);
        url.queryParam("lang", "fr");
        if (!view.getExportedData().isEmpty()) {
            view.getExportedData().forEach(data -> {
                url.queryParam("idThesoConcept", data.getRight() == null ? data.getLeft() : data.getLeft() + "," + data.getRight());
            });
        }

        String urlString = url.build().toString();
        context.redirect(UriBuilder.fromUri(context.getRequestContextPath() + "/d3js/index.html").queryParam("dataUrl", urlString).queryParam("format", "opentheso").build().toString());
    }

    public void exportToNeo4J(String viewId) {
        
        Properties properties = getPrefOfNeo4j();
        if(properties == null){
            showMessage(FacesMessage.SEVERITY_ERROR, "La base de données Neo4J n'est pas paramétrée, ouvrez hikari.properties et faire le changement !");
            return;
        }
        
        //System.out.println("export " + viewId);
        
        GraphObject view = graphService.getView(viewId);
        if (view == null) {
            return;
        }
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        //       String openthesoUrl = "http://localhost:8080/opentheso2";
        String openthesoUrl = context.getRequestScheme() + "://" + context.getRequestServerName()
                + (Objects.equals(context.getRequestServerName(), "localhost") ? ":" + context.getRequestServerPort() : "")
                + context.getApplicationContextPath();

        final String dbUri = "neo4j://" + properties.getProperty("neo4j.serverName") + ":" + properties.getProperty("neo4j.serverPort"); //"neo4j://localhost:7687";
        final String dbUser = properties.getProperty("neo4j.user");//"neo4j";
        final String dbPassword = properties.getProperty("neo4j.password");//"neo4j1234";
        final String dbName = properties.getProperty("neo4j.databaseName");//"neo4j"; //TODO mettre Neo4j avant de commit

        final String thesaurusImportURIWithPlaceholder = openthesoUrl + "/openapi/v1/thesaurus/%THESO_ID%";
        final String branchImportURIWithPlaceholder = openthesoUrl + "/openapi/v1/concept/%THESO_ID%/%TOP_CONCEPT_ID%/expansion?way=down";

        try (var driver = GraphDatabase.driver(dbUri, AuthTokens.basic(dbUser, dbPassword))) {
            driver.verifyConnectivity();
            //System.out.println("Connection estabilished.");

            StringBuilder builder = new StringBuilder();
            view.getExportedData().forEach((data) -> {

                String importURL;

src/main/java/fr/cnrs/opentheso/bean/graph/GraphObject.java
package fr.cnrs.opentheso.bean.graph;

import org.apache.commons.lang3.tuple.ImmutablePair;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author miledrousset
 */

public class GraphObject implements Serializable {

    private int id;
    private String name;
    private String description;
    private List<ImmutablePair<String, String>> exported_data;

    public GraphObject(int id, String name, String description, List<ImmutablePair<String, String>>  exported_data) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.exported_data = new ArrayList<>(exported_data);
    }

    public GraphObject(String name, String description, List<ImmutablePair<String, String>>  exported_data) {
        this.name = name;
        this.description = description;
        this.exported_data = new ArrayList<>(exported_data);
    }

    public GraphObject(int id, String name, String description) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.exported_data = new ArrayList<>();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<ImmutablePair<String, String>>  getExportedData() {
        return exported_data;
    }
}

src/main/java/fr/cnrs/opentheso/ws/openapi/v1/routes/graph/GraphController.java
package fr.cnrs.opentheso.ws.openapi.v1.routes.graph;

import com.zaxxer.hikari.HikariDataSource;
import fr.cnrs.opentheso.ws.openapi.helper.ResponseHelper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import org.apache.commons.lang3.StringUtils;

import javax.ws.rs.*;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.Response;

import static fr.cnrs.opentheso.ws.openapi.helper.CustomMediaType.*;
import static fr.cnrs.opentheso.ws.openapi.helper.DataHelper.*;
import static fr.cnrs.opentheso.ws.openapi.helper.MessageHelper.emptyMessage;
import fr.cnrs.opentheso.ws.openapi.helper.d3jsgraph.GraphD3jsHelper;
import fr.cnrs.opentheso.ws.openapi.helper.d3jsgraph.IdValuePair;
import java.util.ArrayList;
import java.util.List;

@Path("/graph/getData")
public class GraphController {

    @Path("/")
    @GET
    @Produces({APPLICATION_JSON_UTF_8})
    @Operation(summary = "${getDatasForGraphNew.summary}$",
            tags = {"Graph"},
            description = "http://localhost:8080/opentheso2/openapi/v1/graph/getData?lang=fr&idThesoConcept=th3,4&idThesoConcept=th3",
            responses = {
                    @ApiResponse(responseCode = "200", description = "${search.200.description}$", content = {
                            @Content(mediaType = APPLICATION_JSON_UTF_8),
                    }),
                    @ApiResponse(responseCode = "400", description = "${responses.400.description}$"),
                    @ApiResponse(responseCode = "500", description = "${responses.500.description}$")
            })
    public Response getGraph(
            @Parameter(name = "lang",example = "fr", in = ParameterIn.QUERY, schema = @Schema(type = "string"), required = true, description = "${getDatasForGraphNew.lang.description}$") @QueryParam("lang") String lang,
            @Parameter(name = "idThesoConcept", in = ParameterIn.QUERY, schema = @Schema(type = "string"),
                    required = true, example = "th3,4" ,
                    description = "${getDatasForGraphNew.idTheso.description}$") @QueryParam("idThesoConcept") List<String> idThesoConcepts,
                    @Context HttpHeaders headers) {
        
        if(StringUtils.isEmpty(lang)) {
            return ResponseHelper.response(Response.Status.BAD_REQUEST, "La langue est requise", APPLICATION_JSON);            
        }
        if(idThesoConcepts == null || idThesoConcepts.isEmpty()) {
            return ResponseHelper.response(Response.Status.BAD_REQUEST, "Manque les infos du thésaurus et des concepts", APPLICATION_JSON);            
        }        
       
        List<IdValuePair> idValuePairs = new ArrayList<>();
        
        for (String idThesoConcept : idThesoConcepts) {
            String[] elements = idThesoConcept.split(",");
            
            if(elements.length == 2){
                IdValuePair idValuePair = new IdValuePair();
                idValuePair.setIdTheso(elements[0]);
                idValuePair.setIdConcept(elements[1]);
                idValuePairs.add(idValuePair);
            }
            if(elements.length == 1){
                IdValuePair idValuePair = new IdValuePair();
                idValuePair.setIdTheso(elements[0]);
                idValuePairs.add(idValuePair);
            }            
        }
        
        GraphD3jsHelper graphD3jsHelper = new GraphD3jsHelper();
        graphD3jsHelper.initGraph();        
        
        String datas;
        try (HikariDataSource ds = connect()) {
            if (ds == null) {
                return ResponseHelper.errorResponse(Response.Status.INTERNAL_SERVER_ERROR, "Erreur interne du serveur", APPLICATION_JSON_UTF_8);
            }

            for (IdValuePair idValuePair : idValuePairs) {
                if(StringUtils.isEmpty(idValuePair.getIdConcept())){
                    graphD3jsHelper.getGraphByTheso(ds, idValuePair.getIdTheso(), lang);
                } else {
                    graphD3jsHelper.getGraphByConcept(ds, idValuePair.getIdTheso(), idValuePair.getIdConcept(), lang);
                }
            }            
        }
        datas = graphD3jsHelper.getJsonFromNodeGraphD3js();
        if (StringUtils.isEmpty(datas)) {
            return ResponseHelper.response(Response.Status.OK, emptyMessage(APPLICATION_JSON_UTF_8), APPLICATION_JSON_UTF_8);
        } 
        return ResponseHelper.response(Response.Status.OK, datas, APPLICATION_JSON_UTF_8);        
    }        
}

src/main/webapp/graphview/graph.xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>Opentheso</title>

        <link href="../resources/img/icon_opentheso2.png" rel="icon" />

        <link rel="stylesheet" type="text/css" href="../resources/css/all.css" />
        <link rel="stylesheet" type="text/css" href="../resources/css/theme_general.css" />
        <link rel="stylesheet" type="text/css" href="../resources/css/theme_opentheso.css" />
        <link rel="stylesheet" type="text/css" href="../resources/css/composants_opentheso.css" />

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.0/css/all.css"/> 
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.0/css/v4-shims.css"/>
    </h:head>

    <h:body id="page-top" onload="initMenu()">

        <style>
            .ui-dataview .ui-dataview-header {
                border-bottom: 0 none;
                display: none;
            }
        </style>
        <p:idleMonitor timeout="#{connect.timeout}">
            <p:ajax event="idle" listener="#{sessionControl.isTimeout}" />
        </p:idleMonitor>


        <p:growl id="messageIndex" globalOnly="true" showDetail="true"/>

        <h:panelGroup rendered="#{menuBean.checkIfUserIsConnected()}" id="wrapper" style="height: 100vh;" >

            <ui:include src="../commun/menu.xhtml" />

            <div id="content-wrapper" style="width: 100%; height:100%; position:relative; overflow: hidden;">

                <div class="container-fluid">

                    <div class="d-sm-flex align-items-center justify-content-between mb-4" style="margin: 20px; display: flex; justify-content: space-between">
                        <h1 class="h3 mb-0 text-gray-800">
                            <span style="color: #f47b2a">
                                <p:graphicImage value="/resources/img/graph.png"  style="width: 42px; margin-right: 5px;"/> 
                                #{langueBean.getMsg('graph')}
                            </span></h1>

                        <p:commandButton  update="graph-form"
                                          icon="fas fa-sync" styleClass="rounded-button ui-button-outlined"
                                          style="color: #F47B2A"
                                          title="recharger la page"
                                          actionListener="#{dataGraphView.init()}"/>   
                        <p:commandButton value="Nouvelle vue" styleClass="ui-button-success" icon="fa fa-plus"
                                         update="idManageView" oncomplete="PF('manageView').show();" actionListener="#{dataGraphView.initNewViewDialog()}"/>
                    </div>

                    <p:scrollPanel mode="native" style="height: 82vh">
                        <h:form id="graph-form">
                            <p:dataView var="graph_view" value="#{dataGraphView.graphObjects}" rows="6" paginator="true"
                                        paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}" rowsPerPageTemplate="6,12,16"
                                        
                                        layout="grid" gridRowStyleClass="sm:col-2 lg:col-4 xl:col-6">

                                <p:dataViewGridItem>
                                    <div class="row" style="margin-right: 1px; ">
                                        <div class="col-1 offset-11" >
                                            <p:menuButton icon="pi pi-align-justify" >
                                                <p:menuitem value="Modifier la vue"
                                                            icon="fa fa-pen"
                                                            update="idManageView manageViewForm"
                                                            oncomplete="PF('manageView').show();"
                                                            actionListener="#{dataGraphView.initEditViewDialog(graph_view.id)}"/>  
                                                <p:menuitem value="Supprimer la vue"
                                                            icon="fa fa-trash"
                                                            actionListener="#{dataGraphView.removeView(graph_view.id)}"
                                                            update="graph-form"/>
                                            </p:menuButton>
                                        </div>
                                    </div>
                                    <div class="card border-1" style="padding: 10px; margin: 1px">
                                            <div style="height: 150px;">
                                                <p style="font-weight: bold; font-size: 1.15rem; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2; overflow: hidden; text-overflow: ellipsis;">#{graph_view.name}</p>
                                                <p style="text-overflow: ellipsis; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 5; overflow: hidden;">#{graph_view.description}</p>
                                            </div>
                                            <p:dataList value="#{graph_view.exportedData}" var="export" type="none" style="height: 100px;">
                                                <p:chip rendered="#{export.right==null}" label="#{export.left}" styleClass="mr-2" style="color:#601e18; background-color:#ECF8F1 "/>
                                                <p:chip rendered="#{export.right!=null}" label="#{export.left}, #{export.right}" styleClass="mr-2" style="color:#601e18; background-color:#FAEDE5"/>
                                            </p:dataList>
                                        
                                        
                                        
                                        <div class="row">
                                            <div class="col-6">
                                                <p:graphicImage rendered="#{!graph_view.exportedData.isEmpty()}" value="/resources/img/d3js.png" styleClass="ui-icon-custom" style="margin-right: 5px;"/>                                            
                                                <p:commandButton value="Afficher avec D3.js"
                                                                 styleClass="ui-button-success"
                                                                 icon="fa fa-diagram-project"
                                                                 style="margin-left: 0px; "
                                                                 rendered="#{!graph_view.exportedData.isEmpty()}"
                                                                 actionListener="#{dataGraphView.redirectToGraphVisualization(graph_view.id)}" >
                                                </p:commandButton>                                                
                                            </div>

                                            <div class="col-6 ">                                            
                                                <p:graphicImage rendered="#{!graph_view.exportedData.isEmpty()}" value="/resources/img/neo4j.png" styleClass="ui-icon-custom" 
                                                                style="margin-right: 5px;f"/>                                            
                                                <p:commandButton value="Exporter vers Neo4J"
                                                                 styleClass="ui-button-secondary"
                                                                 icon="fa fa-paper-plane"

                                                                 rendered="#{!graph_view.exportedData.isEmpty()}"
                                                                 actionListener="#{dataGraphView.exportToNeo4J(graph_view.id)}"
                                                                 update="messageIndex" >
                                                </p:commandButton>
                                            </div>
                                        </div>                                            

                                    </div>
                                </p:dataViewGridItem>
                            </p:dataView>
                        </h:form>
                    </p:scrollPanel>
                </div>
                <ui:include src="../commun/footer.xhtml" />
                <ui:include src="../dialog/graph/manageView.xhtml" />
            </div>
        </h:panelGroup> 
    </h:body>
</html>

src/main/webapp/graphview/index.xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>Opentheso</title>

        <link href="../resources/img/icon_opentheso2.png" rel="icon" />

        <link rel="stylesheet" type="text/css" href="../resources/css/all.css" />
        <link rel="stylesheet" type="text/css" href="../resources/css/theme_general.css" />
        <link rel="stylesheet" type="text/css" href="../resources/css/theme_opentheso.css" />
        <link rel="stylesheet" type="text/css" href="../resources/css/composants_opentheso.css" />

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.0/css/all.css"/>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.0/css/v4-shims.css"/>
    </h:head>

    <h:body id="page-top" onload="initMenu();" style="overflow-x: hidden;">
        <p:growl id="messageIndex" globalOnly="true" showDetail="true" />


        <div id="wrapper" style="height: 100%">

            <ui:include src="../commun/menu.xhtml" />
            <div id="content-wrapper" style="width: 100%">
                Coucou
            </div>
        </div>


        <ui:include src="../commun/footer.xhtml" />
        <script src="../resources/js/bootstrap.bundle.min.js"></script>
        <script src="../resources/js/jquery.easing.min.js"></script>
        <script src="../resources/js/sb-admin-2.js"></script>
    </h:body>
</html>